# Generated by Django 5.1.3 on 2024-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='image', max_length=500),
            preserve_default=False,
        ),
    ]
