# Generated by Django 5.1.3 on 2025-01-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_movie_description_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='director',
            name='picture',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.URLField(max_length=500),
        ),
    ]
