# Generated by Django 5.1.3 on 2025-01-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_actor_description_director_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
