# Generated by Django 5.1.3 on 2025-01-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_moviepeople_delete_actor_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='name',
        ),
    ]
