# Generated by Django 5.1.3 on 2025-01-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_moviepeople_movieperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
