# Generated by Django 5.1.3 on 2025-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_movie_actors_alter_movie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='movie_pictures/'),
        ),
    ]
