# Generated by Django 5.1.3 on 2025-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieperson',
            name='picture',
            field=models.URLField(max_length=500),
        ),
    ]
